project:
  render: 
    - published-202606-devijver-scb.qmd
    - README.qmd

title: "Should we correct the bias in Confidence Bands for Repeated Functional Data?"
author:
  - name: Emilie Devijver
    corresponding: true
    email: emilie.devijver@univ-grenoble-alpes.fr
    url: https://lig-aptikal.imag.fr/~devijvee/
    orcid: 0000-0002-8360-1834
    affiliations:
      - name: CNRS, Univ. Grenoble Alpes, Grenoble INP, LIG, 38000 Grenoble, France
  - name: Adeline Samson
    email: adeline.leclercq-samson@univ-grenoble-alpes.fr
    url: http://adeline.e-samson.org
    affiliations:
      - name: Univ. Grenoble Alpes, CNRS, Grenoble INP, LJK, 38000 Grenoble, France
date: last-modified
date-modified: last-modified
abstract: >+
 While confidence intervals for finite quantities are well-established, constructing confidence bands for objects of infinite dimension, such as functions, is challenging.  In this paper, we explore the concept of parametric confidence bands for functional data with an orthonormal basis. Specifically, we revisit the method proposed by Sun and Loader, which yields confidence bands for the projection of the regression function in a fixed-dimensional space. This approach can introduce bias into the confidence bands when the dimension of the basis is misspecified. Building on this insight, we introduce a corrected, unbiased confidence band. Surprisingly, our corrected band tends to be wider than that suggested by a naive approach. To address this, we propose a model selection criterion that allows for data-driven estimation of the basis dimension. The bias is then automatically corrected after dimension selection. We illustrate these strategies through an extensive simulation study. We conclude with an application to real data.
keywords: [functional data, repeated data, confidence band, Kac-Rice formulae, bias, dimension selection]
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.57750/nmyg-wg36"
  publisher: "French Statistical Society"
  issn: "2824-7795"
  url: "https://computo-journal.org/published-202606-devijver-scb/"
related-identifiers:
  - relation: IsVersionOf
    type: URL
    identifier: "https://hal.science/hal-04599968v1"
bibliography: references.bib
github-user: computorg
repo: "published-202606-devijver-scb"
status: accepted
format:
  computo-pdf: default
  computo-html: default



